global:
  scrape_interval:     15s # By default, scrape targets every 15 seconds.
  external_labels:
    monitor: 'codelab-monitor'

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'node-exporter'
    scrape_interval: 1s
    static_configs:
      - targets: ['node-exporter:9100']

  - job_name: 'docker'
    scrape_interval: 1s
    static_configs:
      - targets: ['cadvisor:8080']
